### ISSUE TITLE
Make tabs names more visible. Use more white 

### ISSUE THREAD

**Issue by bro-n-bro-2** [bro-n-bro/bro_monitor#71]
![image](https://github.com/bro-n-bro/bro_monitor/assets/89855562/1ca139b1-42e5-4364-ab7a-84b0543d616c)
![image](https://github.com/bro-n-bro/bro_monitor/assets/89855562/10eb4abd-0496-402e-8436-c1df0e74a4d5)
For refference
![image](https://github.com/bro-n-bro/bro_monitor/assets/89855562/6f107b6f-d501-476a-9713-0aaee07d0bf1)

**Comment by irahunt** [comment]
Done. 
Link https://www.figma.com/file/qhmlIKVNDNUFfdkOZqhvnR/%F0%9F%91%8A%F0%9F%8F%BB-bro_n_bro-team?type=design&node-id=5058-94098&mode=design&t=nMGb9vO5Opfzj6eJ-4
<img width="1679" alt="Снимок экрана 2024-02-17 в 21 21 32" src="https://github.com/bro-n-bro/bro_monitor/assets/106156987/03aa06e8-44a6-4212-815a-d64e9011e6ae">

Duplicated on all layouts.
@prevetal @bro-n-bro-2  сhanged to medium font weight instead of regular and updated the color to a lighter shade.
